name: Firebase Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    # Only run on the upstream repo, not forks
    if: github.repository == 'gdsc-utech/gdsc-utech-website'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        env:
          CI: false
        run: npm ci && npm run build
      
      - name: Deploy Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}